apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec:
      containers:
      - name: app
        image: isaoshinohara/boxbattleserver:1
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 30002
      initContainers:
      - name: redis
        image: busybox
        command: ['sh', '-c', 'until nslookup redis; do echo waiting for redis; sleep 2; done;']
