apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec:
      containers:
      - name: app
        image: isaoshinohara/boxbattleserver:1
        ports:
        - containerPort: 30001
