apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 30002
    targetPort: 30002
    nodePort: 30002
  selector:
    app: app
    tier: frontend
